---
apiVersion: serverless.kyma-project.io/v1alpha1
kind: GitRepository
metadata:
    creationTimestamp: null
    name: kyma-serverless-community-hour
    namespace: default
spec:
    url: https://github.com/kwiatekus/kyma-serverless-community-hour.git

---
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
    creationTimestamp: null
    name: sanitize-fn
    namespace: default
spec:
    baseDir: /src/sanitize-fn/
    env:
        - name: eventspecversion
          value: "1.0"
        - name: eventsource
          value: kyma
        - name: eventtype
          value: sap.kyma.custom.acme.payload.sanitised.v1
    reference: main
    runtime: nodejs14
    source: kyma-serverless-community-hour
    type: git

---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
    creationTimestamp: null
    name: data-in
    namespace: default
spec:
    gateway: kyma-gateway.kyma-system.svc.cluster.local
    rules:
        - accessStrategies:
            - handler: allow
          methods:
            - GET
          path: /.*
    service:
        host: data-in
        name: sanitize-fn
        port: 80

