name: sanitize-fn
namespace: default
runtime: nodejs14
source:
    sourceType: git
    url: https://github.com/kwiatekus/kyma-serverless-community-hour.git
    repository: kyma-serverless-community-hour
    reference: main
    baseDir: /src/sanitize-fn/
env:
    - name: eventspecversion
      value: "1.0"
    - name: eventsource
      value: kyma
    - name: eventtype
      value: sap.kyma.custom.acme.payload.sanitised.v1
apiRules:
    - name: data-in
      service:
        host: data-in.c-31cabdf.kyma.ondemand.com
      rules:
        - methods:
            - GET
          accessStrategies:
            - handler: allow
